// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxwgIWaRlgb8ObMm-BoDTniZ1rACzloF0',
    appId: '1:681773028575:web:54cec5c88cf73174cd456a',
    messagingSenderId: '681773028575',
    projectId: 'musicservice-94482',
    authDomain: 'musicservice-94482.firebaseapp.com',
    storageBucket: 'musicservice-94482.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSlWhPyv5lRd6kY7Pw-62ovVw4i4eOG_0',
    appId: '1:681773028575:android:331bb22fd442b648cd456a',
    messagingSenderId: '681773028575',
    projectId: 'musicservice-94482',
    storageBucket: 'musicservice-94482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt5I1xmcVp62SqjakfLoOxIHYNUbLNdXk',
    appId: '1:681773028575:ios:9fd20288e6884a17cd456a',
    messagingSenderId: '681773028575',
    projectId: 'musicservice-94482',
    storageBucket: 'musicservice-94482.firebasestorage.app',
    iosBundleId: 'com.example.musicServicesModule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt5I1xmcVp62SqjakfLoOxIHYNUbLNdXk',
    appId: '1:681773028575:ios:9fd20288e6884a17cd456a',
    messagingSenderId: '681773028575',
    projectId: 'musicservice-94482',
    storageBucket: 'musicservice-94482.firebasestorage.app',
    iosBundleId: 'com.example.musicServicesModule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxwgIWaRlgb8ObMm-BoDTniZ1rACzloF0',
    appId: '1:681773028575:web:18c964368292a808cd456a',
    messagingSenderId: '681773028575',
    projectId: 'musicservice-94482',
    authDomain: 'musicservice-94482.firebaseapp.com',
    storageBucket: 'musicservice-94482.firebasestorage.app',
  );
}
